### ISSUE TITLE
Want to run the agent under `privileged=false` to avoid the risk of container escape

### ISSUE THREAD

**Issue by DomineCore** [deepflowys/deepflow#1172]
找到了一个参考方案，希望对deepflow有帮助https://senberhu.github.io/ebpf/eBPF-AntiRootkit.html

**Comment by mytting** [comment]
@DomineCore `sys_admin`? 
Now that privileged=false has been used, there is a detailed description of permissions：

https://deepflow.yunshan.net/docs/zh/install/overview/#%E8%BF%90%E8%A1%8C%E6%9D%83%E9%99%90%E5%8F%8A%E5%86%85%E6%A0%B8%E8%A6%81%E6%B1%82

**Comment by DomineCore** [comment]
This access is required?

**Comment by mytting** [comment]
> `sys_admin` This access is required?

At present, the k8s node uses setns to obtain the network card correspondence between pod and host, as well as the ip mac and other information of pod network card. Here, sys_admin is required for eBPF.

**Comment by mytting** [comment]
> > `sys_admin` This access is required?
> 
> ## Where `sys_admin` is needed
> * setns is used on the k8s node to obtain the network card correspondence between pod and host, as well as the ip mac of pod network card and other information
> * eBPF

第一个问题可以尝试在节点上使用 arp -n 是否可以获得所有容器网卡的ip mac地址，这在节点上使用 ip r 可以看到本节点pod ip地址路由的一般是可以的，但是在kube-ovn等cni pod ip 路由通过了一个网卡进行中转的一般不可以

**Comment by mytting** [comment]
v6.1.6已支持使用非sys_admin权限部署 ，可以通过修改values去掉sys_admin权限
```yaml
deepflow-agent:
  securityContext: 
    # privileged: true
    capabilities:
      add:
     # - SYS_ADMIN ## Permission required for collecting K8s information and eBPF data
      - SYS_RESOURCE ## Permissions required to collect eBPF data
      - SYS_PTRACE ## Permission required for collecting K8s information
      - NET_ADMIN ## Indicates the permission for collecting AF_PACKET traffic
      - NET_RAW ## Indicates the permission for collecting AF_PACKET traffic
      - IPC_LOCK ## optional MAP_LOCKED MAP_NORESERVE: Indicates the permission for collecting AF_PACKET traffic, It can significantly degrade performance when not available
      -  BPF      ## Optionally, eBPF does not require SYS_ADMIN in kernel Linux 5.8+ and uses a combination of BPF and PERFMON instead
      - PERFMON 
```
