### ISSUE TITLE
Offline deployment

### ISSUE THREAD

**Issue by horsefeng** [deepflowys/deepflow#2363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

环境都是内网，不能开公网在线安装，请问怎么离线安装？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Get offline helm chart:
```
helm repo add deepflow https://deepflowys.github.io/deepflow
helm repo update deepflow
helm pull deepflow/deepflow
```

Push the image to the internal mirror warehouse by yourself and modify values to the address of the internal mirror warehouse:
```yaml
global:
   image:
     ## ghcr Image repository address: ghcr.io/deepflowys/deepflow-ce
     ## Dockerhub Image repository address: deepflowce
     ## AliyunYun Image repository address: registry.cn-beijing.aliyuncs.com/deepflow-ce
     repository: deepflowce
```
