### ISSUE TITLE
[FR] FR-021:  support replica clickhouse table

### ISSUE THREAD

**Issue by zyxfei** [deepflowys/deepflow#2403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In an enterprise environment, based on reliability considerations, we usually use the  external clickhouse cluster with the sharding function enabled. Currently, Deepflow does not support writing to the replicamergetree clickhouse table. We hope to support this feature, thank you

### Use case

in helm chart 
```
externalClickHouse:
    enabled: true  ## Enable external ClickHouse
    type: ep

    ## External ClickHouse clusterName,The default value is 'default', query method:  'select cluster,host_address,port from system.clusters;'
    clusterName: sharding_ha
    enableReplica: true
    ...
```
in deepflow configmap
```
    database: xx
    host: deepflow-external-clickhouse
    port: 9000
    timeout: 60
    user-name: xx
    user-password: xx
    enableReplica: true
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)
